# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2823355165494ad37c677008f95cf29ac62fa88c9a25366c3bd4f15729ef5147aa7a55d0f7161bdb870ce6cc5e422993ff85a97626ccdfd3290b783dc60874fa

test:
  secret_key_base: 2cc80410f457b0d55bbeb42036e5e48cf4f9f3a625d7f765132f1b4b9006c105f444ee7e850bb27ce129f2e3d769be4835dc9f97cacb39f940e23aa02b326a77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
